name: twilio_dart_web
description: A sample web application
dependencies:
  twilio_dart: 
    path: ../../
dev_dependencies:
  build_web_compilers: ^2.0.0
  build_runner: ^1.6.2
  build_test: ^0.10.2
